add custom account doc
koderover/zadig-doc pull request #235
Opened 2022-01-19 08:41 UTC by lilianzhu

Signed-off-by: lilianzhu <zhujiali@koderover.com>

2022-01-19 10:47 UTC, leozhang2018 requested changes

2022-01-19 10:47 UTC, leozhang2018 commented on dev/09.系统设置/03.用户账户集成/08.custom.md
> +目前 Zadig 用户系统采用了开源项目 [dex](https://github.com/dexidp/dex) 作为身份连接器，但 dex 支持的协议列表（[dex 支持的协议](https://dexidp.io/docs/connectors/)）有限，Zadig 则基于 dex 官方库实现了一些标准的扩展，如 OAuth 协议、Portal 接入层等。如果用户自身的账号系统在 Zadi
- 用户系统采用了开源项目 [dex](https://github.com/dexidp/dex) -> 用户系统采用了开源项目 [Dex](https://github.com/dexidp/dex)
- 但 dex 支持的协议列表 -> 但 Dex 支持的协议列表

注意专有名词的大小写。
其余类似。

2022-01-19 10:47 UTC, leozhang2018 commented on dev/09.系统设置/03.用户账户集成/08.custom.md
> +### 步骤 1 ：编写自定义 dex connector
编写自定义 Dex Connector，其余就不标注了。

2022-01-19 10:47 UTC, leozhang2018 commented on dev/09.系统设置/03.用户账户集成/08.custom.md
> +目前 Zadig 用户系统采用了开源项目 [dex](https://github.com/dexidp/dex) 作为身份连接器，但 dex 支持的协议列表（[dex 支持的协议](https://dexidp.io/docs/connectors/)）有限，Zadig 则基于 dex 官方库实现了一些标准的扩展，如 OAuth 协议、Portal 接入层等。如果用户自身的账号系统在 Zadi
这里是否有必要将 Dex 官方支持协议列表，同步放一份，方便用户查阅，所见即所得，不用跳来跳去。
![image](https://user-images.githubusercontent.com/6907296/150115356-f19c4b29-9e3d-48b3-a9ff-44f9062a58bf.png)

2022-01-20 03:27 UTC, jamsman94 commented on dev/09.系统设置/03.用户账户集成/08.custom.md
> +helm upgrade --install ... \
这个东西不那么准确，当时我给出这个命令是在安装时候去用最合适的，单独升级用这个不太好。
具体怎么措辞我没想好，主要需要表达的意思是：
- 在升级的同时做这件事的话，用这个命令
- 如果升级完了中间想要自己开发，建议使用kubectl edit deployment的方式去做
- 自己开发完毕以后，之后每一次zadig的版本升级，都要添加上面所写的两条--set命令去同步

2022-01-20 03:27 UTC, jamsman94 commented on v1.7.1/09.系统设置/02.用户账户集成/08.custom.md
> +    --set dex.image.repository=<您的公开镜像仓库> \
same here

2022-01-20 03:27 UTC, jamsman94 commented on v1.8.0/09.系统设置/03.用户账户集成/08.custom.md
> +    --set dex.image.repository=<您的公开镜像仓库> \
same here

2022-01-20 03:45 UTC, jamsman94 commented on dev/09.系统设置/03.用户账户集成/08.custom.md
> +helm upgrade --install ... \
- kubectl get deployment | grep dex 找到dex的deployment
- kubectl set image deployment/<dex的deployment> dex=<new-image> --record

2022-01-20 06:36 UTC, jamsman94 approved these changes
LGTM

2022-01-20 17:21 UTC, fansi404 commented on v1.7.1/09.系统设置/02.用户账户集成/08.custom.md
> +|RefreshConnector|实现后可以更新客户端 claims|mock/Callback、bitbucketcloud、atlassiancrowed、gitea、github、gitlab、google、ldap、linkedin、microsoft、mock/passwordConnector、oidc、passwordDB(位于dex/server/server.go)|
`位于dex/server/server.go`

the same

2022-01-20 17:21 UTC, fansi404 commented on v1.7.1/09.系统设置/02.用户账户集成/08.custom.md
> +|PasswordConnector|1. 简单使用用户名密码方式登录授权获取用户信息的。<br>2. Dex 和账号系统的交互是同步的|keystone、atlassiancrowed、ldap、mock/passwordConnector、passwordDB(位于dex/server/server.go)|
`位于dex/server/server.go`

1. 中英文空格
2. 建议 link

2022-01-20 17:21 UTC, fansi404 commented on v1.7.1/09.系统设置/02.用户账户集成/08.custom.md
> +此 connector 实现了 CallbackConnector interface，以下为 OAuth connector 代码
加个换行，否则 view 效果：


![image](https://user-images.githubusercontent.com/89375976/150386431-e6da93f9-3535-423d-a072-161ecb19008d.png)

2022-01-20 17:21 UTC, fansi404 commented on v1.7.1/09.系统设置/02.用户账户集成/08.custom.md
> +2. 运行 `make docker-image` 构建镜像后上传
这里有个背景，需要在 Makefile 所在的目录来运行。

1. 这边可以改为`在 xxxx 目录下运行....`，不过有能力实施自定义账号系统接入的同学大概率应该知道这个背景，可能也问题不大。
2. 读了之后的第一感觉有点困惑：运行 make docker-image 之后，是只构建镜像，还是既给我做了构建镜像，又做了上传。看了下代码，是前者。这边可以修改下：运行 make docker-image 构建镜像，并上传镜像至自己的公开镜像仓库

2022-01-20 17:21 UTC, fansi404 commented on v1.7.1/09.系统设置/02.用户账户集成/08.custom.md
> +1. 更改 Makefile 中的 `DOCKER_REPO` 变量为自己的公开镜像仓库
建议：`[Makefile](link)`

2022-01-20 17:21 UTC, fansi404 commented on v1.7.1/09.系统设置/02.用户账户集成/08.custom.md
> +3. 安装 Zadig 的时候用自定义的 Dex 镜像覆盖配置中 Zadig Dex 镜像
`配置中 Zadig Dex 镜像` ？Zadig Dex 镜像？困惑，二者到底啥关系 @panxunying

要表达的意思是：安装 Zadig 的时候用自定义的镜像覆盖 Dex 的原始镜像？

2022-01-20 17:29 UTC, fansi404 commented on dev/09.系统设置/03.用户账户集成/08.custom.md
> +![account_custom](../_images/account_custom_1.png)
图中的 YAML 配置内容是从哪里来的？通篇都没有这部分配置，用户怎么去获得这个？@panxunying

2022-01-20 17:37 UTC, fansi404 commented on dev/09.系统设置/03.用户账户集成/08.custom.md
> +![account_custom](../_images/account_custom.jpeg)
图中文案存在中英文空格问题，如果好改的话可以 fix 一下，保持风格统一，也体现我们对于文档专业性的诉求 @panxunying

2022-01-21 01:02 UTC, lilianzhu commented on dev/09.系统设置/03.用户账户集成/08.custom.md
> +目前 Zadig 用户系统采用了开源项目 [Dex](https://github.com/dexidp/dex) 作为身份连接器，但 Dex 支持的协议列表（[Dex 支持的协议](https://dexidp.io/docs/connectors/)）有限，Zadig 则基于 Dex 官方库实现了一些标准的扩展，如 OAuth 协议等。如果用户自身的账号系统在 Zadig 官方支持之外，可以
前面部分需要介绍

2022-01-21 01:04 UTC, lilianzhu commented on v1.7.1/09.系统设置/02.用户账户集成/08.custom.md
> +- 目前 Dex Connector 接口定义于 dex/connector/connector.go 中，官方抽象了`PasswordConnector`、`CallbackConnector`、`RefreshConnector`、`SAMLConnector` 四种接口，用户可以根据自己账号系统情况实现自己的 Connector，参考 dex/connector 的各种 connector
fixed

2022-01-21 01:06 UTC, lilianzhu commented on v1.7.1/09.系统设置/02.用户账户集成/08.custom.md
> +|PasswordConnector|1. 简单使用用户名密码方式登录授权获取用户信息的。<br>2. Dex 和账号系统的交互是同步的|keystone、atlassiancrowed、ldap、mock/passwordConnector、passwordDB(位于dex/server/server.go)|
fixed

2022-01-21 01:07 UTC, lilianzhu commented on v1.7.1/09.系统设置/02.用户账户集成/08.custom.md
> +此 connector 实现了 CallbackConnector interface，以下为 OAuth connector 代码
fixed

2022-01-21 01:10 UTC, lilianzhu commented on v1.7.1/09.系统设置/02.用户账户集成/08.custom.md
> +3. 安装 Zadig 的时候用自定义的 Dex 镜像覆盖配置中 Zadig Dex 镜像
fixed

2022-01-21 03:44 UTC, fansi404 approved these changes
LGTM

2022-01-21 03:51 UTC, merged